name: Publish to npm

on:
  push:
    tags:
      - "*.*.*" # Triggers when a tag following semantic versioning (e.g., v1.0.0) is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
